apiVersion: apps/v1
kind: Deployment
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    name: <name>
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: <name>
  template:
    metadata:
      labels:
        name: <name>
    spec:
      containers:
        - name: <name>
          image: 3dsinteractive/kafka:2.0-custom
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER_ID
              value: <kafkaBrokerID>
            - name: KAFKA_PORT_NUMBER
              value: <kafkaPortNumber>
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INSIDE://<name>:9092
            - name: KAFKA_LISTENERS
              value: INSIDE://:9092
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_AUTO_CREATE_TOPIC_ENABLE
              value: "false"
            - name: KAFKA_NUM_PARTITIONS
              value: <kafkaNumPartitions>
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: <kafkaZookeeperConnect>
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INSIDE:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INSIDE
            - name: KAFKA_HEAP_OPTS
              value: <kafkaHeapOpts>
          resources:
            requests:
              memory: <minMem>
              cpu: <minCpu>
            limits:
              memory: <maxMem>
              cpu: <maxCpu>
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 300
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 30
            failureThreshold: 5
          ports:
            - containerPort: 9092
              name: kfk9092
---
apiVersion: v1
kind: Service
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    name: <name>
spec:
  selector:
    name: <name>
  ports:
    - name: kfk9092
      port: 9092
      protocol: TCP
  clusterIP: None
