apiVersion: apps/v1
kind: Deployment
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    name: <name>
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: <name>
  template:
    metadata:
      labels:
        name: <name>
    spec:
      nodeSelector:
        env: <clientId>
        db: <nodeLabel>
      containers:
        - name: <name>
          image: 3dsinteractive/redis:5.0
          imagePullPolicy: Always
          ports:
            - name: redis6379
              containerPort: 6379
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          resources:
            requests:
              memory: <minMem>
              cpu: <minCpu>
            limits:
              memory: <maxMem>
              cpu: <maxCpu>
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 300
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 30
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    name: <name>
spec:
  selector:
    name: <name>
  ports:
    - port: 6379
      name: redis6379
      targetPort: 6379
      protocol: TCP
  clusterIP: None
